### PR TITLE
Fix for unlock issue (#10) + fix for lock / unlock actions in "Settings"

### PR DESCRIPTION
**Pull request by fopat**
Hi,

Here is a proposal to fix the unlock issue + a fix for another issue I found while testing, also linked to the "Unlock for staking only" option.
I have described my fix here: https://github.com/ignitioncoin/ignitioncoin/issues/10

Please tell me if I need to change anything :)

### CODE REVIEW

**Comment by fopat** [comment]
After some thoughts, the 2nd fix could by improved by:
- Handling the update of fWalletUnlockStakingOnly in CWallet since CWallet is responsible for this variable
- Forcing fWalletUnlockStakingOnly to false in CWallet::Lock
- Adding a parameter to CWallet::Unlock to set the value of fWalletUnlockStakingOnly

I will do the update later in the day.

**Comment by fopat** [comment]
Update done. Pull request ready to be reviewed.

**Comment by fopat** [comment]
In fact, https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsdialog.cpp#L302 already returned Locked before and requests an unlock without my fix.
However, what happens next is that when validating the passphrase dialog to unlock for sending, the CWallet::Unlock function exits at the beginning, before the passphrase is even tested, because it considers the wallet as already unlock and thus does not try to fully unlock it.

We could add a UnlockedForStakingOnly value, but I was afraid it could have more impact because getEncryptionStatus() is used at other places (darksend, message sending, etc.)

IMHO, the lock / unlock mechanism still needs some deeper improvements because it is not perfect now. For example, we could analyze which part of it should be in WalletModel and which part in CWallet and refactor it.
But this will be a bigger task with more impact.

Tell me how you want me to go on on this subject.
Shall I modify the fix? Shall I start working on a deeper refactorization of the lock / unlock process?

PS: about the "Unlock for staking only", for now I only set it to false for the case in which it is hidden, but I can set it to false always if you want.

**Comment by Matthematic** [comment]
I'd suggest merging this as is just to get a fix out there, and either you or I can dive deeper into it later. 

How did you only set it to false if it is hidden? It looks to be set to false in the initialization of the dialog and before the switch, so I'd think it would run on all scenarios. I'm not too familiar with the workflow this code touches though so feel free to teach me.

**Comment by Matthematic** [comment]
When you do merge, please squash the commits so the history doesn't get bloated.

**Comment by TechniumUnlimited** [comment]
Sorry I dont think I squashed ^_^

**Pull request merged**
