### PR TITLE
Send coins dialog messages modal

### LINKED ISSUE #36: New version does not alert when sending with full balance
New version does not alert when sending with full balance without deducting fee -- should give warning/info pop-up

"olie480 🔥 - Last Monday at 12:50 PM
Thought I would post this. Just downloaded the new wallet (Mac), and it looks great. One thing I noticed is that I was trying to send my whole IC balance in my wallet to another address, I clicked on the Send button, but it wasn't doing anything. I then tried sending a lower amount, and then the button worked. I think some sort of an alert  should show up letting the user know that they must deduct 0.001 from the balance they're trying to send. Or take the balance sent, deduct the 0.001, and warn the user of the full amount minus the fee. I must have pressed it about 20 times thinking it wasn't working. lol
didn’t want it to get lost in the other channels, but yeah, it only popped up something when I deducted 0.00001 (I believe that’s the fee?) from the total withdraw amount.
Example: So I tried doing my whole balance which was 0.0028743 and nothing popped up until I used the amount of 0.0028643
Sorry, my memory is a little off on what the fee was but I started at the end, deducting 1 from each of the numbers on the right"

### PR DESCRIPTION
**Pull request by fopat**
Replace the system notifications from the send coins dialog by modal messages.
System notifications are apparently not shown on Mac OS. Furthermore, the error messages for sending coins have no reason to be system notifications but should rather be message boxes.

Tested on Linux (Debian), Windows 10 and Windows 7.

Resolves #36

### CODE REVIEW

**Comment by fopat** [comment]
@TechniumUnlimited With this fix, the error messages are displayed using a QMessageBox instead of a system notification, so the behaviour will be the same on every OS: a QT modal message box will be displayed.

**Comment by TechniumUnlimited** [comment]
@fopat Let me see about re-testing this on windows, does it force window to become active even if it is minimized do you know? If it's much more intrusive on windows, maybe we could add a lever or controller option to switch between the modes?

**Comment by fopat** [comment]
It should not, the change is only in the SendCoinsDialog::processSendCoinsReturn function, so only after an action is done to send a coin.
In all the other cases, the notification system remains unchanged.

**Comment by TechniumUnlimited** [comment]
hmm @fopat can we retarget this to dev branch, then can merge

**Comment by fopat** [comment]
@TechniumUnlimited done!

**Comment by TechniumUnlimited** [comment]
Thanks

**Pull request merged**
