### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by CircuitBreaker88**
Last

### CODE REVIEW

**Comment by CircuitBreaker88** [comment]
Fixed @TechniumUnlimited

**Comment by TechniumUnlimited** [comment]
Doesn't seem to be compiling

**Comment by CircuitBreaker88** [comment]
Added 3 New RPC Commands for Atomic Swaps - as well as BIP 065

**Comment by CircuitBreaker88** [comment]
modded getinfo and getblock slightly

**Comment by CircuitBreaker88** [comment]
@TechniumUnlimited We should merge this to get a release prepared 

If you want you can add me as collab on this repo

**Comment by TechniumUnlimited** [comment]
We can merge to 1.3 branch

**Pull request merged**
